Repository BEAST-Fitting/beast, pull requests merged in 2019-11, with the labels that each got.

#438 updates to simulate_obs.py
  beast/tools/simulate_obs.py
Labels: stars

#443 skipping isochrone download test temporarily
  beast/physicsmodel/stars/tests/test_padova_isochrone_download.py
Labels: bug

#428 WIP: Adding more plot tests
  beast/plotting/plot_cmd.py
  beast/plotting/plot_cmd_with_fits.py
  beast/plotting/plot_filters.py
  beast/plotting/tests/baseline/test_indiv_plot.png
  beast/plotting/tests/baseline/test_plot_cmd.png
  beast/plotting/tests/baseline/test_plot_cmd_with_fits.png
  beast/plotting/tests/baseline/test_plot_filters.png
  beast/plotting/tests/test_plots.py
Labels: plotting, tests

#445 Update how catalogs are cut
  beast/tools/create_background_density_map.py
  beast/tools/cut_catalogs.py
  docs/workflow.rst
Labels: artificial stars

#446 Travis xfail for isochrone download
  beast/physicsmodel/stars/tests/test_padova_isochrone_download.py
Labels: tests

#444 coverage skipped for script 'main' sections
  beast/plotting/make_ds9_region_file.py
  beast/plotting/plot_cmd.py
  beast/plotting/plot_cmd_with_fits.py
  beast/plotting/plot_filters.py
  beast/plotting/plot_good_bad.py
  beast/plotting/plot_indiv_fit.py
  beast/plotting/plot_noisemodel.py
  beast/plotting/plot_param_err.py
  beast/plotting/plot_param_recovery.py
  beast/plotting/plot_param_vs_chi2min.py
  beast/plotting/plot_region_diags.py
  beast/plotting/plot_stats_check.py
  beast/plotting/plot_triangle.py
  beast/tools/condense_beast_results_spatial.py
  beast/tools/create_background_density_map.py
  beast/tools/cut_catalogs.py
  beast/tools/density_map.py
  beast/tools/get_libfiles.py
  beast/tools/merge_beast_stats.py
  beast/tools/remove_filters.py
  beast/tools/reorder_beast_results_spatial.py
  beast/tools/run/create_filenames.py
  beast/tools/run/create_obsmodel.py
  beast/tools/run/create_physicsmodel.py
  beast/tools/run/make_ast_inputs.py
  beast/tools/run/make_trim_scripts.py
  beast/tools/run/merge_files.py
  beast/tools/run/run_fitting.py
  beast/tools/setup_batch_beast_fit.py
  beast/tools/setup_batch_beast_trim.py
  beast/tools/simulate_obs.py
  beast/tools/split_catalog_using_map.py
  beast/tools/subdivide_obscat_by_source_density.py
  beast/tools/verify_params.py
  beast/tools/write_sbatch_file.py
Labels: tests
