Repository BEAST-Fitting/beast, pull requests merged in 2020-12, with the labels that each got.

#674 Fixed a small bug in make_ast_inputs.py when using random_pick method
  beast/tools/run/make_ast_inputs.py
Labels: artificial stars, bug

#670 Updates to main docs page
  docs/beast_development.rst
  docs/example.rst
  docs/index.rst
  docs/install.rst
  docs/new_user_interface.rst
  docs/publications.rst
Labels: documentation

#677 inverted T axis, added minor ticks
  beast/plotting/plot_param_err.py
Labels: plotting

#678 Remove incorrectly recovered ASTs
  beast/observationmodel/noisemodel/toothpick.py
  beast/plotting/plot_toothpick_details.py
Labels: artificial stars, bug

#662 Use asdf files for testing compare_spec_type and star_type_probability
  beast/tests/test_regresscheck.py
  beast/tools/compare_spec_type.py
Labels: tests

#679 Adding log binning option for source density
  beast/observationmodel/ast/make_ast_input_list.py
  beast/observationmodel/ast/make_ast_xy_list.py
  beast/tools/cut_catalogs.py
  beast/tools/density_map.py
  beast/tools/run/make_ast_inputs.py
  beast/tools/split_catalog_using_map.py
  docs/workflow.rst
Labels: artificial stars

#684 Graphics for file flow
  beast/main.py
  beast/plotting/plot_graphic_file_flow.py
  beast/plotting/plot_graphic_model.py
  docs/beast_graphical_model.rst
  docs/images/beast-graphic-file-flow-sourceden.png
  docs/images/beast-graphic-file-flow-subgrid.png
  docs/index.rst
  docs/workflow.rst
Labels: documentation
