Repository BEAST-Fitting/beast, pull requests merged in 2020-05, with the labels that each got.

#534 Fix for ambiguous filters in remove_filters
  beast/tools/read_beast_data.py
  beast/tools/remove_filters.py
  beast/tools/tests/test_remove_filters.py
Labels: bug

#551 Test for the write_sbatch_file tool
  beast/tools/tests/test_write_sbatch_file.py
  beast/tools/write_sbatch_file.py
Labels: tests, tools

#555 Updating v1.4 to the latest master
  README.rst
  beast/fitting/fit.py
  beast/fitting/fit_metrics/common.py
  beast/fitting/pdf1d.py
  beast/fitting/pdf2d.py
  beast/fitting/trim_grid.py
  beast/observationmodel/ast/make_ast_input_list.py
  beast/observationmodel/noisemodel/generic_noisemodel.py
  beast/observationmodel/noisemodel/tests/test_generic_noisemodel.py
  beast/observationmodel/observations.py
  beast/physicsmodel/grid_and_prior_weights.py
  beast/physicsmodel/grid_weights_stars.py
  beast/physicsmodel/model_grid.py
  beast/physicsmodel/prior_weights_dust.py
  beast/physicsmodel/prior_weights_stars.py
  beast/physicsmodel/tests/test_dust_prior_weights.py
  beast/physicsmodel/tests/test_extinguished_sed_grid.py
  beast/physicsmodel/tests/test_stellar_grid_weights.py
  beast/physicsmodel/tests/test_stellar_prior_weights.py
  beast/plotting/plot_ast_histogram.py
  beast/plotting/plot_completeness.py
  beast/plotting/plot_mag_hist.py
  beast/plotting/plot_noisemodel.py
  beast/tests/helpers.py
  beast/tools/compare_spec_type.py
  beast/tools/convert_hdf5_to_fits.py
  beast/tools/data/effective_temperature.txt
  beast/tools/data/surface_gravity.txt
  beast/tools/read_beast_data.py
  beast/tools/remove_filters.py
  beast/tools/run/create_filenames.py
  beast/tools/run/create_obsmodel.py
  beast/tools/run/create_physicsmodel.py
  beast/tools/run/run_fitting.py
  beast/tools/setup_batch_beast_trim.py
  beast/tools/simulate_obs.py
  beast/tools/star_type_probability.py
  beast/tools/subgridding_tools.py
  beast/tools/tests/test_beast_data.py
  beast/tools/tests/test_compare_spec_type.py
  beast/tools/tests/test_convert_hdf5_to_fits.py
  beast/tools/tests/test_remove_filters.py
  beast/tools/tests/test_star_type_probability.py
  beast/tools/tests/test_subgridding_tools.py
  beast/tools/tests/test_verify_warnings.py
  beast/tools/tests/test_write_sbatch_file.py
  beast/tools/verify_params.py
  beast/tools/write_sbatch_file.py
  docs/analysis_tools.rst
  docs/beast_development.rst
  docs/beast_priors.rst
  docs/beast_setup.rst
  docs/fitting_api.rst
  docs/generating_asts.rst
  docs/index.rst
  docs/other_tools.rst
  docs/simulations.rst
  docs/tools_api.rst
  docs/workflow.rst
  setup.cfg
Labels: packaging

#501 Skip trimming files if trimmed versions already exist
  beast/tools/setup_batch_beast_trim.py
  beast/tools/trim_many_via_obsdata.py
Labels: enhancement

#562 Small fix to use_rate keyword in create_obsmodel.py
  beast/tools/run/create_obsmodel.py
Labels: bug

#563 Add missing argparse option in remove_filters.py
  beast/tools/remove_filters.py
Labels: bug
