Repository BEAST-Fitting/beast, pull requests merged in 2020-10, with the labels that each got.

#629 Simulations updated to address bug of too much mass
  beast/observationmodel/observations.py
  beast/plotting/plot_cmd.py
  docs/images/metal_small_sim_f475w_prior_plot.png
  docs/simulations.rst
Labels: bug

#631 Removed code style issues.
  beast/physicsmodel/stars/ezmist/README.md
  beast/physicsmodel/stars/ezpadova/README.md
Labels: bug, documentation

#624 beast graphical model docs
  beast/main.py
  beast/plotting/plot_graphic_model.py
  docs/beast_graphical_model.rst
  docs/images/beast-graphic-math.png
  docs/images/beast-graphic-text.png
  docs/index.rst
  setup.cfg
Labels: documentation

#636 removing NaNs from ast results
  beast/observationmodel/noisemodel/toothpick.py
  beast/tools/run/run_fitting.py
Labels: artificial stars, bug, fitting

#634 fixes to beast_info, AST pick_positions, and stats merging
  beast/observationmodel/ast/make_ast_xy_list.py
  beast/physicsmodel/model_grid.py
  beast/tools/beast_info.py
  beast/tools/merge_beast_stats.py
  beast/tools/run/make_ast_inputs.py
  beast/tools/subgridding_tools.py
Labels: artificial stars, fitting

#642 Replaced all occurences of np.empty() with np.zeros()
  beast/observationmodel/noisemodel/absflux_covmat.py
  beast/observationmodel/noisemodel/toothpick.py
  beast/observationmodel/noisemodel/trunchen.py
  beast/observationmodel/observations.py
  beast/physicsmodel/creategrid.py
  beast/physicsmodel/grid_weights_stars.py
  beast/physicsmodel/prior_weights_stars.py
  beast/physicsmodel/stars/isochrone.py
  beast/physicsmodel/stars/kurucz/generate.py
  beast/physicsmodel/stars/simpletable.py
  beast/physicsmodel/stars/stellib.py
  beast/plotting/plot_indiv_fit.py
  beast/tools/reorder_beast_results_spatial.py
Labels: bug

#637 Edits to supplementing BEAST-optimized ASTs
  beast/observationmodel/ast/make_ast_input_list.py
  beast/tools/run/make_ast_inputs.py
Labels: artificial stars

#643 Edited convention for source density binning
  beast/observationmodel/ast/make_ast_xy_list.py
  beast/tools/run/make_ast_inputs.py
  beast/tools/split_catalog_using_map.py
  docs/workflow.rst
Labels: artificial stars, bug

#644 Add more options to use simulate_obs to properly simulate ASTs
  beast/observationmodel/observations.py
  beast/tools/simulate_obs.py
  docs/simulations.rst
Labels: simulations
