Repository BEAST-Fitting/beast, pull requests merged in 2020-07, with the labels that each got.

#600 Address codestyle errors
  beast/fitting/fit.py
  beast/fitting/fit_metrics/__init__.py
  beast/observationmodel/noisemodel/trunchen.py
  beast/physicsmodel/creategrid.py
  beast/physicsmodel/stars/ezmist/__init__.py
  beast/physicsmodel/stars/kurucz/generate.py
  beast/physicsmodel/stars/simpletable.py
  beast/plotting/plot_indiv_pdfs.py
  beast/tests/test_regresscheck.py
  beast/tools/helpers.py
  beast/tools/run/create_filenames.py
  beast/tools/run/create_obsmodel.py
  beast/tools/run/helper_functions.py
  beast/tools/setup_batch_beast_fit.py
  beast/tools/split_catalog_using_map.py
  setup.cfg
Labels: bug

#601 Add tool to calculate observation depths
  beast/tests/test_regresscheck.py
  beast/tools/calc_depth_from_completeness.py
  docs/other_tools.rst
Labels: enhancement, gold-star, observation

#602 adding input flux/rate/vega to simulation output table
  beast/observationmodel/observations.py
  beast/tools/simulate_obs.py
  docs/simulations.rst
  setup.cfg
Labels: simulations

#603 fix plot_cmd.py savefig keyword
  beast/plotting/plot_cmd.py
  docs/simulations.rst
Labels: bug, plotting

#575 Supplement the existing input ASTs
  beast/observationmodel/ast/make_ast_input_list.py
  beast/tools/run/make_ast_inputs.py
  docs/generating_asts.rst
  docs/workflow.rst
Labels: artificial stars

#609 Added units to derived parameters
  docs/outputs.rst
Labels: documentation

#607 Fix attribute name for settings object
  beast/tools/run/create_physicsmodel.py
  beast/tools/setup_batch_beast_fit.py
Labels: bug
