Repository BEAST-Fitting/beast, pull requests merged in 2020-11, with the labels that each got.

#655 Updating sedgrid tests
  beast/physicsmodel/tests/test_grid.py
Labels: bug, tests

#648 APE17 updates
  docs/Makefile
  docs/beast_development.rst
  docs/install.rst
  setup.cfg
Labels: documentation

#656 Revert accidental changes to pick_positions
  beast/observationmodel/ast/make_ast_xy_list.py
Labels: artificial stars, bug

#657 Documentation for how to specify mag and color cuts for supplemented ASTs
  beast/observationmodel/ast/make_ast_input_list.py
  docs/generating_asts.rst
Labels: artificial stars, documentation

#654 Add optional erosion to AST placement region
  beast/observationmodel/ast/make_ast_xy_list.py
  beast/tools/run/make_ast_inputs.py
  docs/beast_setup.rst
Labels: artificial stars
