Repository BEAST-Fitting/beast, pull requests merged in 2021-03, with the labels that each got.

#700 remove unused Nfilter parameter in toothpick style model selection
  beast/observationmodel/ast/make_ast_input_list.py
  beast/tools/run/make_ast_inputs.py
Labels: artificial stars, bug

#699 Cleanup toothpick observation model calculation and fix simulate_obs bug
  beast/observationmodel/noisemodel/generic_noisemodel.py
  beast/observationmodel/noisemodel/toothpick.py
  beast/observationmodel/observations.py
  beast/plotting/plot_toothpick_details.py
  beast/tests/test_regresscheck.py
  beast/tools/run/create_obsmodel.py
  beast/tools/simulate_obs.py
Labels: artificial stars, bug, simulations

#703 Adding erosion step to source density map creation
  beast/observationmodel/ast/make_ast_xy_list.py
  beast/tools/create_background_density_map.py
Labels: artificial stars

#702 Modify plot noisemodel and plot_toothpick_detail
  beast/plotting/plot_noisemodel.py
  beast/plotting/plot_toothpick_details.py
Labels: observation

#705 Checking sd parameter settings with hasattr
  beast/tools/split_catalog_using_map.py
Labels: artificial stars, bug

#645 add code that plots ast info
  beast/plotting/plot_ast_diagnostics.py
Labels: artificial stars, plotting
