Repository BEAST-Fitting/beast, pull requests merged in 2021-01, with the labels that each got.

#689 explicitly read table in 1st extension, hdu=1
  beast/fitting/fit.py
Labels: bug

#685 Add info about using [options.package_data] in setup.cfg
  docs/beast_development.rst
Labels: documentation

#691 allow best legend location; fix matplotlib 3.3 rqmt
  beast/plotting/plot_indiv_fit.py
Labels: plotting

#664 cleanup/fixes for plot_cmd_with_fits.py
  beast/plotting/plot_cmd_with_fits.py
Labels: plotting

#687 partial merge to check results before subgrid fitting is complete
  beast/tools/run/merge_files.py
  beast/tools/subgridding_tools.py
  docs/workflow.rst
Labels: fitting

#692 Suppl ast filename
  beast/tools/run/make_ast_inputs.py
  docs/workflow.rst
Labels: artificial stars
