Repository BEAST-Fitting/beast, pull requests merged in 2024-05, with the labels that each got.

#805 updating tox for latest python and github actions
  .github/workflows/tox-tests.yml
  beast/plotting/plot_graphic_file_flow.py
  tox.ini
Labels: bug, packaging

#807 Fixed random_seds selection bug
  beast/tools/run/make_ast_inputs.py
Labels: bug, simulations

#810 Teeny tiny update to README.rst
  README.rst
Labels: bug, documentation

#799 adding in ACS SBC, WFC3 and ACS narrow, and JWST filters and enhancing the filter plotting routine
  .github/workflows/tox-tests.yml
  beast/observationmodel/tests/test_filters_and_vega_consistent.py
  beast/plotting/plot_filters.py
  beast/tests/test_regresscheck.py
  beast/tools/get_libfiles.py
  beast/tools/make_libfile.py
  docs/beast_development.rst
  docs/beast_filters.rst
  docs/beast_setup.rst
  docs/index.rst
  setup.cfg
  tox.ini
Labels: documentation, observation, tests, gold-star
