Repository BEAST-Fitting/beast, pull requests merged in 2024-08, with the labels that each got.

#818 update to zero weight model warning info
  beast/fitting/fit.py
Labels: tests

#820 Add Roman filters to make_libfile
  beast/tools/make_libfile.py
  docs/beast_filters.rst
Labels: observation

#822 updating coverage python version
  .github/workflows/tox-tests.yml
Labels: tests

#821 modifications to support megabeast simulations
  beast/observationmodel/ast/make_ast_input_list.py
  beast/physicsmodel/creategrid.py
  beast/physicsmodel/grid_and_prior_weights.py
  beast/plotting/plot_cmd.py
  beast/tests/helpers.py
Labels: megabeast
